---
# vars file for mail-server-install
domain: lab.bgdn.io
mail_hostname: mail.{{ domain }}
ldap_server: 192.168.88.201
ldap_dn_user: _mail_svc
ldap_dn_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35363439303130306439306536323137653164346462373338636362353138623536653130366663
          3464353838623236663763323636346637623365353765660a356233633164636462336361623535
          62646631323764643239313432646233633363386163366466303234636637633035316431636530
          3832383264663031350a316630343037663666643636656161366663363565333061336134383762
          6337
ldap_search_base: cn=users,cn=accounts,dc=lab,dc=bgdn,dc=io
ldap_groups_search_base: cn=groups,cn=accounts,dc=ecm,dc=blogic,dc=ru
vmail_path: /mnt/vmail
php_version: 7.4
cert_folder: /etc/letsencrypt/live/{{ mail_hostname }}
local_net: 192.168.88.0/24
sys_pkg:
  - htop 
  - mc 
  - mlocate 
  - ncdu 
  - vim 
  - wget 
  - curl
  - nc
  - tar
certbot_pkg:
  - httpd
  - certbot 
  - python3-certbot-apache
  - mod_ssl
dovecot_pkg: 
  - dovecot
  - dovecot-pigeonhole
postfix_pkg:
  - postfix
  - postfix-ldap
roundcube_pkg:
  - sqlite
  - php
  - php-imap
  - php-mbstring
  - php-pear
  - php-mcrypt
  - php-intl
  - php-ldap
  - php-pear-Net-SMTP
  - php-pear-Net-Sieve
  - php-pear-Mail-Mime
  - php-pear-Net-IDNA2
opendkim_pkg:
  - opendkim
  - opendkim-tools
fail2ban_pkg:
  - fail2ban
  - fail2ban-firewalld
fw_ports:
  - 80/tcp
  - 443/tcp
  - 25/tcp
  - 110/tcp
  - 143/tcp
  - 587/tcp
  - 465/tcp
  - 993/tcp
  - 995/tcp
roundcube_version: 1.5.3
roundcube: roundcubemail-{{ roundcube_version }}
roundcube_src: https://github.com/roundcube/roundcubemail/releases/download/{{ roundcube_version }}/roundcubemail-{{ roundcube_version }}-complete.tar.gz
roundcube_db_path: /var/lib/roundcubemail
roundcube_db_user: roundcube
roundcube_web_path: /var/www/roundcubemail
region: Europe/Moscow
dkim_path: /etc/postfix/dkim