---
- hosts: all
  become: yes
  roles: 
     - mail-server-install
  when: 
  - "ansible_facts['os_family'] == 'RedHat' or ansible_facts['os_family'] == 'Rocky'"
  -  ansible_distribution_major_version | int >= 8
