- name: Install dovecot
  yum: 
    name: '{{ dovecot_pkg }}'
    state: present
  notify: 
    - Enable dovecot
    - Start dovecot

- name: Create group for vmail user
  group: 
    name: vmail
    gid: 1010

- name: Add the vmail user with a specific uid and a primary group
  user: 
    name: vmail
    uid: 1010
    group: vmail
    home: '{{ vmail_path }}'

- name: Create directory for dovecot logs
  file:
    path: /var/log/dovecot
    state: directory
    owner: vmail
    group: dovecot
    mode: '0775'

- name: Creating an empty file
  file:
    path: /var/log/dovecot/{{ item }}
    state: touch
    owner: vmail
    group: dovecot
  loop:
    - main.log
    - info.log
    - debug.log
    - lda-errors.log
    - lda-deliver.log
    - lmtp.log

- name: Create vmail folder
  file: 
    path: '{{ vmail_path }}/{{ domain }}'
    state: directory
    owner: vmail
    group: dovecot
    mode: '0775'

- name: Create directory for shared folders
  file:
    path: '{{ vmail_path }}/shared-folders'
    state: directory
    owner: vmail
    group: vmail
    mode: '0775'

- name: Check dovecot conf.d folder
  stat:
    path: /etc/dovecot/conf.d
  register: conf_d

- name: Renaming. Copy dovecot conf.d folder
  copy: 
    remote_src: True
    src: /etc/dovecot/conf.d
    dest: /etc/dovecot/conf.d.bak
  when: conf_d.stat.exists

- name: Renaming. Delete dovecot conf.d folder
  file: 
    path: /etc/dovecot/conf.d
    state: absent
  when: conf_d.stat.exists

- name: Check dovecot.conf file
  stat:
    path: /etc/dovecot/dovecot.conf
  register: dovecot_conf

- name: Renaming. Copy dovecot.conf
  copy: 
    remote_src: True
    src: /etc/dovecot/dovecot.conf
    dest: /etc/dovecot/dovecot.conf.bak
  when: dovecot_conf.stat.exists

- name: Renaming. Delete dovecot.conf
  file: 
    path: /etc/dovecot.conf
    state: absent
  when: dovecot_conf.stat.exists

- name: Generate dovecot.conf
  template: 
    src: templates/dovecot.conf.j2
    dest: /etc/dovecot/dovecot.conf
    mode: '0664'
  notify: Restart dovecot

- name: Generate dovecot-ldap.conf
  template:
    src: templates/dovecot-ldap.conf.j2
    dest: /etc/dovecot/dovecot-ldap.conf
    mode: '0664'
  notify: Restart dovecot