- name: Install dovecot
  yum: 
    name: '{{ dovecot_pkg }}'
    state: present
  notify: Enable dovecot

#- name: Enabling and starting {{ svc }} service
#  service:
#    name: '{{ svc }}'
#    state: started
#    enabled: true

#- name: Rename dovecot conf.d folder
#  command: mv /etc/dovecot/conf.d /etc/dovecot/conf.d.bak

- name: Check dovecot conf.d folder
  stat:
    path: /etc/dovecot/conf.d
  register: conf_d

- name: Renaming. Copy dovecot conf.d folder
  copy: 
    remote_src: True
    src: /etc/dovecot/conf.d
    dest: /etc/dovecot/conf.d.bak
  when: conf_d.stat.exists

- name: Renaming. Delete dovecot conf.d folder
  file: 
    path: /etc/dovecot/conf.d
    state: absent
  when: conf.d.stat.exists

#- name: Rename dovecot.conf
#  command: mv /etc/dovecot/dovecot.conf /etc/dovecot/dovecot.conf.bak

- name: Renaming. Copy dovecot.conf
  copy: 
    remote_src: True
    src: /etc/dovecot/dovecot.conf
    dest: /etc/dovecot/dovecot.conf.bak

- name: Renaming. Delete dovecot.conf
  file: 
    path: /etc/dovecot.conf
    state: absent

- name: Generate dovecot.conf
  template: 
    src: templates/dovecot.conf.j2
    dest: /etc/dovecot/dovecot.conf
    mode: 0555

- name: Create group for vmail user
  group: 
    name: vmail
    gid: 1010

- name: Add the vmail user with a specific uid and a primary group
  user: 
    name: vmail
    uid: 1010
    group: vmail
    home: /mnt/vmail/

- name: Change vmail folder permission
  file: 
    path: /mnt/vmail
    owner: vmail
    group: vmail

- name: Create vmail folder
  file: 
    path: /mnt/vmail
    state: directory
    owner: vmail
    group: dovecot
    mode: 0664

- name: Generate dovecot-ldap.conf
  template:
    src: templates/dovecot-ldap.conf.j2
    dest: /etc/dovecot/dovecot-ldap.conf
    mode: 0555

- name: Create directory for dovecot logs
  file:
    path: /var/log/dovecot
    state: directory
    owner: vmail
    group: dovecot
    mode: 0664

- name: Creating an empty file
  file:
    path: /var/log/dovecot/{{ item }}
    state: touch
    owner: vmail
    group: dovecot
  loop:
    - main.log
    - info.log
    - debug.log
    - lda-errors.log
    - lda-deliver.log
    - lmtp.log

- name: Change dovecot log folder permission
  file: 
    path: /var/log/dovecot/
    owner: vmail
    group: dovecot
    recurse: yes

- name: Create directory for shared folders
  file:
    path: /mnt/vmail/shared-folders
    state: directory
    owner: vmail
    group: vmail
    mode: 0664
  notify:
    - Restart postfix
    - Restart dovecot