- name: Install fail2ban
  yum: 
    name: '{{ fail2ban_pkg }}'
    state: present
  notify: 
    - Enable fail2ban
    - Start fail2ban

- name: Copy fail2ban postfix filter
  copy: 
    src: files/postfix-sasl.conf
    dest: '/etc/fail2ban/filter.d/postfix-sasl.conf'
    owner: root
    group: root
    mode: '0644'
  notify: Restart fail2ban

- name: Copy fail2ban config
  copy: 
    src: files/jail.local
    dest: '/etc/fail2ban/jail.local'
    owner: root
    group: root
    mode: '0644'
  notify: Restart fail2ban