---
- include_tasks: "postfix.yml"
  when: 
    - "ansible_facts['os_family'] == 'RedHat' or ansible_facts['os_family'] == 'Rocky'"
    -  ansible_distribution_major_version | int >= 8
- include_tasks: "dovecot.yml"
  when: 
    - "ansible_facts['os_family'] == 'RedHat' or ansible_facts['os_family'] == 'Rocky'"
    -  ansible_distribution_major_version | int >= 8
- include_tasks: "roundcube.yml"
  when: 
    - "ansible_facts['os_family'] == 'RedHat' or ansible_facts['os_family'] == 'Rocky'"
    -  ansible_distribution_major_version | int >= 8
#- include_tasks: "opendkim.yml"
#  when: "ansible_facts['os_family'] == 'RedHat' or ansible_facts['os_family'] == 'Rocky'"
#  when: server_type=='external'