
- name: Install opendkim packages
  yum: 
    name: '{{ opendkim_pkg }}'
    enablerepo: crb
    state: present
  notify: Enable opendkim

- name: Create opendkim folder
  file: 
    path: /etc/postfix/dkim
    state: directory
    owner: root
    group: opendkim

- name: Check signing key
  stat: 
    path: '{{ dkim_path }}/mail.{{ domain }}.private'
  register: dkim_key

- name: Generate signing key
  command: opendkim-genkey -D {{ dkim_path }}/ -d {{ domain }} -s mail
  when: not dkim_key.stat.exists

- name: Check private key
  stat:
    path: '{{ dkim_path }}/mail.private'
  register: mail_private

- name: Renaming. Copy private key
  copy: 
    remote_src: True
    src: '{{ dkim_path }}/mail.private'
    dest: '{{ dkim_path }}/mail.{{ domain }}.private'
  notify: Restart opendkim
  when: mail_private.stat.exists

- name: Renaming. Delete private key
  file: 
    path: '{{ dkim_path }}/mail.private'
    state: absent
  when: mail_private.stat.exists

- name: Check public key
  stat:
    path: '{{ dkim_path }}/mail.txt'
  register: mail_public

- name: Renaming. Copy public key
  copy: 
    remote_src: True
    src: '{{ dkim_path }}/mail.txt'
    dest: '{{ dkim_path }}/mail.{{ domain }}.txt'
  notify: Restart opendkim
  when: mail_public.stat.exists

- name: Renaming. Delete public key
  file: 
    path: '{{ dkim_path }}/mail.txt'
    state: absent
  when: mail_public.stat.exists

- name: Create keytable
  copy:
    dest: '{{ dkim_path }}/keytable'
    content: 'mail._domainkey.{{ domain }} {{ domain }}:mail:/etc/postfix/dkim/mail.{{ domain }}.private'
  notify: Restart opendkim

- name: Create signingtable
  copy:
    dest: '{{ dkim_path }}/signingtable'
    content: '*@{{ domain }} mail._domainkey.{{ domain }}'
  notify: Restart opendkim

- name: Change opendkim keys permission
  file: 
    path: '{{ dkim_path }}/'
    owner: opendkim
    group: opendkim
    recurse: yes
    mode: '0755'

- name: Generate opendkin config
  template: 
    src: templates/opendkim.conf.j2
    dest: /etc/opendkim.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart opendkim