---
- name: Add repo epel
  yum: 
    name: epel-release
    state: present
  when: 
    - "ansible_facts['os_family'] == 'RedHat' or ansible_facts['os_family'] == 'Rocky'"

- name: Install sys-utils
  yum: 
    name: '{{ sys_pkg }}'
    state: present

- name: Open port 
  firewalld:
    port: '{{ item }}'
    permanent: yes
    state: enabled
  notify: Reload firewall
  loop: '{{ fw_ports }}'

- name: Disable selinux
  selinux: state=disabled

- name: Install postfix
  yum: 
    name: '{{ postfix_pkg }}'
    state: present
  notify: Enable postfix

- name: Check postfix main.cf file
  stat:
    path: /etc/postfix/main.cf
  register: main_cf

- name: Renaming. Copy postfix main.cf file
  copy: 
    remote_src: True
    src: /etc/postfix/main.cf
    dest: /etc/postfix/main.cf.bak
  when: main_cf.stat.exists

- name: Renaming. Delete postfix main.cf file
  file: 
    path: /etc/postfix/main.cf
    state: absent
  when: main_cf.stat.exists

- name: Generate postfix main.cf
  template: 
    src: templates/main.cf.j2
    dest: /etc/postfix/main.cf
    mode: 0555

- name: Create directory for postfix ldap configs
  file:
    path: /etc/postfix/ldap
    state: directory
    owner: root
    group: root
    mode: 0644

- name: Generate postfix virtual map configs for ldap
  template: 
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: 0555
  loop:
    - { src: 'templates/virtual_alias_maps.cf.j2', dest: '/etc/postfix/ldap/virtual_alias_maps.cf' }
    - { src: 'templates/virtual_mailbox_maps.cf.j2', dest: '/etc/postfix/ldap/virtual_mailbox_maps.cf' }

- name: Copy postfix tls_policy_maps
  copy: 
    src: files/tls_policy_maps
    dest: /etc/postfix/
    mode: 0555

- name: Generate postfix tls_policy_maps
  command: postmap /etc/postfix/tls_policy_maps

- name: Check postfix master.cf file
  stat:
    path: /etc/postfix/master.cf
  register: master_cf

- name: Renaming. Copy postfix master.cf file
  copy: 
    remote_src: True
    src: /etc/postfix/master.cf
    dest: /etc/postfix/master.cf.bak
  when: master_cf.stat.exists

- name: Renaming. Delete postfix master.cf file
  file: 
    path: /etc/postfix/master.cf
    state: absent
  when: master_cf.stat.exists

- name: Copy postfix master.cf
  copy: 
    src: files/master.cf
    dest: /etc/postfix/
    mode: 0555

- name: Generate postfix sender and recipient bcc maps
  template: 
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: 0555
  loop:
    - { src: 'templates/recipient_bcc_maps.j2', dest: '/etc/postfix/recipient_bcc_maps' }
    - { src: 'templates/sender_bcc_maps.j2', dest: '/etc/postfix/sender_bcc_maps' }

- name: Generate postfix sender and recipient bcc maps
  command: postmap /etc/postfix/{{ item }}
  loop:
    - recipient_bcc_maps
    - sender_bcc_maps
  notify: Restart postfix