---
- name: Add repo epel
  yum: 
    name: epel-release
    state: present
  when: 
    - "ansible_facts['os_family'] == 'RedHat' or ansible_facts['os_family'] == 'Rocky'"

- name: Install sys-utils
  yum: 
    name: "{{ packages }}"
    state: present
  vars: 
    packages:
      - htop 
      - mc 
      - mlocate 
      - ncdu 
      - vim 
      - wget 
      - curl
      - nc

- name: Open port 
  firewalld:
    port: '{{ item }}'
    permanent: yes
    state: enabled
  with_items:
    - 25/tcp
    - 110/tcp
    - 143/tcp
    - 587/udp
    - 465/udp
    - 993/udp
    - 995/udp

- name: Restart service
  service:
    name : firewalld
    state: reloaded

- name: Disable selinux
  selinux:
    state: disabled