---
- name: Add remi repo key
  rpm_key:
    state: present
    key: https://rpms.remirepo.net/RPM-GPG-KEY-remi2021

- name: Install remi repo
  yum: 
    name: "{{ packages }}"
    state: present
#   disable_gpg_check: yes
  vars: 
    packages:
      - dnf-utils 
      - http://rpms.remirepo.net/enterprise/remi-release-9.rpm 

- name: Enable php module from remi repo
  copy:
    dest: /etc/dnf/modules.d/php.module
    content: |
      [php]
      name=php
      stream=remi-{{ php_version }}
      profiles=
      state=enabled

- name: Disable remi-safe repo
  ini_file:
    path: /etc/yum.repos.d/remi-safe.repo
    section: remi-safe
    option: state
    value: disabled
    no_extra_spaces: yes

- name: install env for roundcube
  yum: 
    name: '{{ packages }}'
    enablerepo: remi
    state: present
  vars: 
    packages:
      - httpd
      - php
      - php-imap
      - php-mbstring
      - php-pear
      - php-mcrypt
      - php-intl
      - php-ldap
      - php-pear-Net-SMTP
      - php-pear-Net-Sieve
      - php-pear-Mail-Mime
      - php-pear-Net-IDNA2
  notify: Enable httpd

- name: Correct php timezone
  replace:
    path: /etc/php.ini
    regexp: ';date.timezone ='
    replace: 'date.timezone = {{ region }}'
    backup: yes

- name: Download roundcube
  get_url:
    url: '{{ roundcube_src }}'
    dest: /root/roundcubemail.tar.gz
    mode: '0640'

- name: Extract roundcube
  unarchive:
    src: /root/roundcubemail.tar.gz
    dest: /var/www/html/roundcube
    remote_src: yes

#tar xzvf roundcubemail-1.5.3-complete.tar.gz
#mkdir /var/www/html/roundcubemail
#cp -R /root/roundcubemail-1.5.3/* /var/www/html/roundcubemail
#chown -R apache. /var/www/html/roundcubemail

#    dnf install httpd php mariadb mariadb-server php-imap php-mysqlnd php-mbstring

#   dnf --enablerepo=remi install php-pear php-mcrypt php-intl php-ldap php-pear-Net-SMTP php-pear-Net-Sieve php-pear-Mail-Mime php-pear-Net-IDNA2




#systemctl restart httpd php-fpm