---
- name: Add remi repo key
  rpm_key:
    state: present
    key: https://rpms.remirepo.net/RPM-GPG-KEY-remi2021

- name: Install remi repo
  yum: 
    name: http://rpms.remirepo.net/enterprise/remi-release-9.rpm 
    state: present
#   disable_gpg_check: yes
#  vars: 
#    packages:
#      - dnf-utils 
#      - http://rpms.remirepo.net/enterprise/remi-release-9.rpm 

- name: Enable php module from remi repo
  copy:
    dest: /etc/dnf/modules.d/php.module
    content: |
      [php]
      name=php
      stream=remi-{{ php_version }}
      profiles=
      state=enabled

- name: Disable remi-safe repo
  ini_file:
    path: /etc/yum.repos.d/remi-safe.repo
    section: remi-safe
    option: state
    value: disabled
    no_extra_spaces: yes

- name: Install env for roundcube
  yum: 
    name: '{{ roundcube_pkg }}'
    enablerepo: remi
    state: present
  notify: Enable httpd

- name: Correct php settings
  replace:
    path: /etc/php.ini
    regexp: '{{ item.regexp }}'
    replace: '{{ item.replace }}'
    backup: yes
  loop:
    - regexp: ';date.timezone ='
      replace: 'date.timezone = {{ region }}'
    - regexp: 'upload_max_filesize ='
      replace: 'upload_max_filesize = 30M'
    - regexp: 'post_max_size ='
      replace: 'post_max_size = 30M'

#- name: Correct php settings
#  lineinfile:
#    path: /etc/httpd/conf/httpd.conf
#    regexp: '{{item.from}}'
#    line: '{{item.to}}'
#        backup: yes
#   with_items:
#         - { from: ';date.timezone =', to: 'date.timezone = {{ region }}'}
#         - { from: 'upload_max_filesize', to: 'ServerAdmin aksarav@devopsjunction.com'}
#         - { from: 'post_max_size', to: 'LogLevel debug'}

- name: Download roundcube
  get_url:
    url: '{{ roundcube_src }}'
    dest: /root/roundcubemail.tar.gz
    mode: '0640'

#- name: Create roundcube folder
#  file: 
#    path: /var/www/html/roundcube
#    state: directory
#    owner: apache
#    group: apache
#    mode: 0664

- name: Extract roundcube
  unarchive:
    src: /root/roundcubemail.tar.gz
    dest: /root/
    remote_src: yes

- name: Copy roundcube folder to the document folder
  copy: 
    remote_src: True
    src: /root/{{ roundcube }}/
    dest: /var/www/html/
 #   directory_mode: yes

- name: Create roundcube DB folder
  file: 
    path: '{{ roundcube_db_path }}'
    state: directory
    owner: apache
    group: apache
    mode: 0664

- name: Initialize DB
  command:
    cmd: "sqlite3 -init {{ roundcube_html_path }}/SQL/sqlite.initial.sql {{ roundcube_db_path }}/sqlite.db '.quit'"
    creates: '{{ roundcube_db_path }}/sqlite.db'

- name: Generate DES-key
  command: 
    cmd: cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 24 | head -n 1
  register: des_key

#- name: Sync roundcube folder to the apache document folder
#  synchronize:
#    src: /root/{{ roundcube }}
#    dest: /var/www/html/

- name: Generate roundcube config
  template: 
    src: templates/config.inc.php.j2
    dest: /var/www/html/config/config.inc.php
    owner: apache
    group: apache
    mode: 0555

- name: Copy roundcube siev plugin config
  copy: 
    src: files/config.inc.php
    dest: /var/www/html/plugins/managesieve/
    owner: apache
    group: apache
    mode: 0555

- name: Change roundcube folder permission
  file: 
    path: /var/www/html/
    owner: apache
    group: apache
    recurse: yes

- name: Delete installer roundcube folder 
  file: 
    path: /var/www/html/webmail/installer
    state: absent

- name: Correct roundcube default domain
  replace:
    path: /var/www/html/config/defaults.inc.php
    regexp: "$config['username_domain'] ="
    replace: "$config['username_domain'] = '{{ domain }}';"
    backup: yes
  notify: Restart httpd