---
- name: Add remi repo key
  rpm_key:
    state: present
    key: https://rpms.remirepo.net/RPM-GPG-KEY-remi2021

- name: Install remi repo
  yum: 
    name: http://rpms.remirepo.net/enterprise/remi-release-9.rpm 
    state: present

- name: Enable php module from remi repo
  copy:
    dest: /etc/dnf/modules.d/php.module
    content: |
      [php]
      name=php
      stream=remi-{{ php_version }}
      profiles=
      state=enabled

- name: Disable remi-safe repo
  ini_file:
    path: /etc/yum.repos.d/remi-safe.repo
    section: remi-safe
    option: state
    value: disabled
    no_extra_spaces: yes

- name: Install env for roundcube
  yum: 
    name: '{{ roundcube_pkg }}'
    enablerepo: remi
    state: present
  notify: Enable httpd

- name: Correct php settings
  replace:
    path: /etc/php.ini
    regexp: '{{ item.regexp }}'
    replace: '{{ item.replace }}'
    backup: yes
  notify: Restart httpd
  loop:
    - regexp: ';date.timezone ='
      replace: 'date.timezone = {{ region }}'
    - regexp: 'upload_max_filesize ='
      replace: 'upload_max_filesize = 30M'
    - regexp: 'post_max_size ='
      replace: 'post_max_size = 30M'

- name: Download roundcube
  get_url:
    url: '{{ roundcube_src }}'
    dest: /root/roundcubemail.tar.gz
    mode: '0640'

- name: Extract roundcube
  unarchive:
    src: /root/roundcubemail.tar.gz
    dest: /root/
    remote_src: yes

- name: Copy roundcube folder to the document folder
  copy: 
    remote_src: True
    src: /root/{{ roundcube }}/
    dest: '{{ roundcube_html_path }}/'

- name: Create roundcube DB folder
  file: 
    path: '{{ roundcube_db_path }}'
    state: directory
    owner: apache
    group: apache

- name: Initialize DB
  command:
    cmd: "sqlite3 -init {{ roundcube_html_path }}/SQL/sqlite.initial.sql {{ roundcube_db_path }}/sqlite.db '.quit'"
    creates: '{{ roundcube_db_path }}/sqlite.db'

- name: Change roundcube DB permission
  file: 
    path: '{{ roundcube_db_path }}'
    owner: apache
    group: apache
    recurse: yes
    mode: '0775'

- name: Generate DES-key
  shell: cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 24 | head -n 1
  register: des_key

- name: Generate roundcube config
  template: 
    src: templates/config.inc.php.j2
    dest: '{{ roundcube_html_path }}/config/config.inc.php'
    owner: apache
    group: apache
    mode: '0644'

- name: Copy roundcube sieve plugin config
  copy: 
    src: files/sieve_config.inc.php
    dest: '{{ roundcube_html_path }}/plugins/managesieve/config.inc.php'
    owner: apache
    group: apache
    mode: '0644'

- name: Copy roundcube newmail notifier plugin config
  copy: 
    src: files/newmail_notifier_config.inc.php
    dest: '{{ roundcube_html_path }}/plugins/newmail_notifier/config.inc.php'
    owner: apache
    group: apache
    mode: '0644'

- name: Copy roundcube zipdownload plugin config
  copy: 
    src: files/zipdownload_config.inc.php
    dest: '{{ roundcube_html_path }}/plugins/zipdownload/config.inc.php'
    owner: apache
    group: apache
    mode: '0644'

- name: Change roundcube folder permission
  file: 
    path: '{{ roundcube_html_path }}'
    owner: apache
    group: apache
    recurse: yes

- name: Delete installer roundcube folder 
  file: 
    path: '{{ roundcube_html_path }}/installer'
    state: absent

- name: Correct roundcube default domain
  replace:
    path: '{{ roundcube_html_path }}/config/defaults.inc.php'
    regexp: '^\$config\[''username_domain''\] = \''''\;'
    replace: "$config['username_domain'] = '{{ domain }}';"
    backup: yes