---
- name: Reload firewall
  service:
    name : firewalld
    state: reloaded

- name: Enable postfix
  service: 
    name: postfix
    state: restarted

- name: Start postfix
  service: 
    name: postfix
    state: started

- name: Restart postfix
  service:
    name: postfix
    enabled: yes

- name: Enable dovecot
  service: 
    name: dovecot
    enabled: yes

- name: Start dovecot
  service: 
    name: dovecot
    state: started

- name: Restart dovecot
  service: 
    name: dovecot
    state: restarted

- name: Enable httpd
  service:
    name: httpd
    enabled: yes

- name: Restart httpd
  service: 
    name: httpd
    state: restarted